### ISSUE TITLE
出版日期

### ISSUE THREAD

**Issue by SiChiTong** [jiuyewxy/ros_arm_tutorials#1]
感謝分享相關資訊。請問書本甚麼時間出版？

**Comment by jiuyewxy** [comment]
本书已经出版，目前可在淘宝上进行购买。

【淘宝】https://m.tb.cn/h.UEIyoaE?tk=exqfdMFff1C CZ3457 「ROS机械臂开发与实践」
点击链接直接打开 或者 淘宝搜索直接打开

过几天当当和京东上会同步购买链接。

感谢支持。

**Comment by SiChiTong** [comment]
感謝通知 已購買
感謝分享這麼好的教材
