### ISSUE TITLE
ROS Noetic版本：catkin_make失败，Built target ecl_socket_client卡滞

### ISSUE THREAD

**Issue by Dale-Git** [jiuyewxy/ros_arm_tutorials#2]

**Comment by Dale-Git** [comment]
> ROS [Noetic版本：catkin_make的时候，Built target ecl_socket_client卡滞，重启虚拟机很多次，没有catkin_make成功。

已经解决，我把虚拟机的内存大小由4096MB提升到了8192MB，但是还是经过了多次catkin_make才顺利完成。

**Comment by jiuyewxy** [comment]
学ROS我个人不太建议用虚拟机，会遇到很多问题。
