### ISSUE TITLE
xarm_moveit_demo的CMakeLists.txt与package.xml的配置有不一致

### ISSUE THREAD

**Issue by Dale-Git** [jiuyewxy/ros_arm_tutorials#3]
xarm_moveit_demo的CMakeLists.txt与package.xml的配置有不一致，CMakeLists.txt的一个依赖包是tf2，package.xml的配置为tf而非tf2。
但是可以顺利运行。不太清楚为什么可以顺利运行。

ros_arm_tutorials-noetic-devel的xarm_moveit_demo的CMakeLists.txt依赖的包如下：
find_package(catkin REQUIRED COMPONENTS
  roscpp
  rospy
  sensor_msgs
  std_msgs
  tf2
  moveit_core
  moveit_ros_planning
  moveit_ros_planning_interface
)
在同目录（ros_arm_tutorials-noetic-devel的xarm_moveit_demo）的package.xml的配置如下：
 <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>tf</build_depend>
  <build_depend>moveit_core</build_depend>
  <build_depend>moveit_ros_planning</build_depend>
  <build_depend>moveit_ros_planning_interface</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>sensor_msgs</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>tf</build_export_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>moveit_core</exec_depend>
  <exec_depend>moveit_ros_planning</exec_depend>
  <exec_depend>moveit_ros_planning_interface</exec_depend>

**Comment by jiuyewxy** [comment]
是我的疏忽。
因为xarm_moveit_demo编译和运行时并没有依赖tf和TF2包，所有没有报错，实际可以删除这几行。
