### ISSUE TITLE
请问机器臂模型是颠倒的怎么解决呢？

### ISSUE THREAD

**Issue by wyysert** [jiuyewxy/ros_arm_tutorials#4]
![2024-08-10 15-58-50 的屏幕截图](https://github.com/user-attachments/assets/bd8c72ff-aef4-4d8d-bc67-0f8fc242ef2c)
请问机器臂模型是颠倒的怎么解决呢？

**Comment by jiuyewxy** [comment]
参考书里urdf章节和TF章节，应该是你的机械臂的base_link的坐标系关系没设置正确

rviz查看上加上TF插件，更能明确的看到你的一些TF设置
