### ISSUE TITLE
安装依赖并编译代码失败

### ISSUE THREAD

**Issue by blackbadguy** [jiuyewxy/ros_arm_tutorials#5]
在github代码下载完成后，在终端依次输入以下命令安装依赖包并编译代码报错：
1、rosdep install --from-paths src -i -y
报错：
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
xarm_driver: Cannot locate rosdep definition for [serial]
2、sudo apt-get install ros-melodic-moveit*
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 ros-melodic-moveit*
E: 无法按照 glob ‘ros-melodic-moveit*’ 找到任何软件包
E: 无法按照正则表达式 ros-melodic-moveit* 找到任何软件包
3、sudo apt-get install ros-melodic-ar-track-alvar
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 ros-melodic-ar-track-alvar
4、catkin_make
Base path: /home/zp/tutorial_ws
The specified base path "/home/zp/tutorial_ws" contains a package but "catkin_make" must be invoked in the root of workspace

**Comment by jiuyewxy** [comment]
参考着书里的安装步骤安装ROS正确的版本以及设置rosdep

注意下运行rosdep和catkin_make命令的目录，要在工作空间根目录下运行

**Comment by jiuyewxy** [comment]
@blackbadguy
